version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
     - "8080:80"
    environment:
      #Make sure the databse url maches the AWS credentials
     - /Users/sam_little_j/Drawzy/backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
       - "8081:80"
      