"""alter ispublic to boolean

Revision ID: 381439ebbafe
Revises: 405c63565108
Create Date: 2025-05-28 21:12:02.472151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381439ebbafe'
down_revision: Union[str, None] = '405c63565108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'rooms',
        'is_public',
        existing_type=sa.String(length=5),
        type_=sa.Boolean(),
        nullable=False,
        server_default=sa.text('false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'rooms',
        'is_public',
        existing_type=sa.Boolean(),
        type_=sa.String(length=5),
        nullable=True,
        server_default=sa.text("'false'"),
    )
    # ### end Alembic commands ###
