"""add is_public to the room

Revision ID: 405c63565108
Revises: b163c8f2e660
Create Date: 2025-05-28 19:38:37.309451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '405c63565108'
down_revision: Union[str, None] = 'b163c8f2e660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false'))
   )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_public')
    
    # ### end Alembic commands ###
