"""Added theme table

Revision ID: 7066611d8e3e
Revises: cbb0fb438dd4
Create Date: 2025-06-27 14:52:59.497174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7066611d8e3e'
down_revision: Union[str, None] = 'cbb0fb438dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('text', sa.String(length=100), nullable=False))
    op.drop_index(op.f('test'), table_name='themes')
    op.create_unique_constraint(None, 'themes', ['text'])
    op.drop_column('themes', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('test', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'themes', type_='unique')
    op.create_index(op.f('test'), 'themes', ['test'], unique=True)
    op.drop_column('themes', 'text')
    # ### end Alembic commands ###
