"""Added theme table

Revision ID: cbb0fb438dd4
Revises: ce67c7d0529f
Create Date: 2025-06-27 14:27:02.712213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb0fb438dd4'
down_revision: Union[str, None] = 'ce67c7d0529f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test')
    )
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_table('themes')
    # ### end Alembic commands ###
